---
apiVersion: v1
kind: Namespace
metadata:
  name: sish
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sish
  name: sish
  namespace: sish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sish
  template:
    metadata:
      labels:
        app: sish
    spec:
      containers:
      - name: nix
        image: nixos/nix
        command:
        - /bin/sh
        - -c
        - |
            nix profile install --extra-experimental-features nix-command --extra-experimental-features flakes nixpkgs#sish && \
            mkdir -p deploy/keys deploy/pubkeys deploy/ssl && \
            exec sish --authentication=false --load-templates=false --http-address=:8080 --ssh-address=:2222 \
            -d 1.1.1.1 --bind-random-ports=false --bind-random-subdomains=false --bind-random-aliases=false
        ports:
        - name: http
          containerPort: 8080
        - name: ssh
          containerPort: 2222
        - name: randomport
          containerPort: 5000 # Will be dynamically exposed through ssh
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sish
  name: sish
  namespace: sish
spec:
  externalIPs:
  - 1.1.1.1 # not an actual IP address we own
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 2222
    protocol: TCP
    targetPort: 2222
    name: ssh
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: randomport
  selector:
    app: sish
  type: LoadBalancer
